import { type ContractAddress } from '@midnight-ntwrk/compact-runtime';
import { CompiledContract } from '@midnight-ntwrk/compact-js';
import { deployContract, findDeployedContract } from '@midnight-ntwrk/midnight-js/contracts';
import { assertIsContractAddress } from '@midnight-ntwrk/midnight-js/utils';
import { Oru, type OruPrivateState, createOruPrivateState, witnesses } from '@oru/contract';
import { type OruProviders, type DeployedOruContract, OruPrivateStateId } from './common-types';

const oruCompiledContract = CompiledContract.make('oru', Oru.Contract).pipe(
  CompiledContract.withWitnesses(witnesses),
  CompiledContract.withCompiledFileAssets('oru'),
);

/** SHA-256 via the browser's native Web Crypto API (no Node polyfill needed). */
const sha256 = async (bytes: Uint8Array): Promise<Uint8Array> =>
  new Uint8Array(await crypto.subtle.digest('SHA-256', bytes.slice()));

/** Hash arbitrary job details (title/description) into a 32-byte commitment. */
export const hashDetails = (details: string): Promise<Uint8Array> => sha256(new TextEncoder().encode(details));

/** A random 32-byte salt for the budget commitment. */
export const randomSalt = (): Uint8Array => crypto.getRandomValues(new Uint8Array(32));

/**
 * Derive the Oru marketplace secret key deterministically from the wallet's
 * shielded coin public key. The DApp Connector never exposes the wallet's
 * seed to the page, so — unlike the CLI, which derives from the seed — the
 * browser derives from a stable public identifier instead. Only the hash of
 * this key (further hashed in-circuit) ever reaches the chain.
 */
export const deriveOruSecretKey = async (shieldedCoinPublicKeyHex: string): Promise<Uint8Array> =>
  sha256(new TextEncoder().encode(`oru:web:sk:${shieldedCoinPublicKeyHex}`));

export const getOruLedgerState = async (
  providers: OruProviders,
  contractAddress: ContractAddress,
): Promise<Oru.Ledger | null> => {
  assertIsContractAddress(contractAddress);
  const contractState = await providers.publicDataProvider.queryContractState(contractAddress);
  return contractState != null ? Oru.ledger(contractState.data) : null;
};

export const joinOruContract = async (
  providers: OruProviders,
  contractAddress: string,
  privateState: OruPrivateState,
): Promise<DeployedOruContract> =>
  findDeployedContract(providers, {
    contractAddress,
    compiledContract: oruCompiledContract,
    privateStateId: OruPrivateStateId,
    initialPrivateState: privateState,
  });

export const deployOruContract = async (
  providers: OruProviders,
  privateState: OruPrivateState,
): Promise<DeployedOruContract> =>
  deployContract(providers, {
    compiledContract: oruCompiledContract,
    privateStateId: OruPrivateStateId,
    initialPrivateState: privateState,
  });

export interface PostedOrder {
  orderId: bigint;
  budgetSalt: Uint8Array;
  txId: string;
  blockHeight: number;
}

/**
 * Post a work order. The details string and budget never leave this browser
 * tab as plaintext; only their commitments are sent to the chain, and the
 * proof that they were computed correctly is generated by the wallet
 * extension without the private inputs ever being displayed in the UI.
 */
export const postOrder = async (
  contract: DeployedOruContract,
  details: string,
  budget: bigint,
  requireVerified: boolean = false,
): Promise<PostedOrder> => {
  const budgetSalt = randomSalt();
  const detailsHash = await hashDetails(details);
  const finalized = await contract.callTx.postOrder(detailsHash, budget, budgetSalt, requireVerified);
  return {
    orderId: finalized.private.result,
    budgetSalt,
    txId: finalized.public.txId,
    blockHeight: finalized.public.blockHeight,
  };
};

export interface JoinedAllowlist {
  txId: string;
  blockHeight: number;
}

/**
 * Join the verified-freelancer allowlist. Requires having completed at
 * least one order already — proven from the caller's own private
 * completed-order count, never disclosing anything beyond the same
 * pseudonymous identity hash used everywhere else in the contract.
 */
export const joinAllowlist = async (contract: DeployedOruContract): Promise<JoinedAllowlist> => {
  const finalized = await contract.callTx.joinAllowlist();
  return { txId: finalized.public.txId, blockHeight: finalized.public.blockHeight };
};

export { createOruPrivateState };
